version: '3.4' 

services:

  api:
    image: woodgrovebank-api:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: api
    ports:
      - 5000:80
      - 11111:11111
      - 30000:30000

  admin:
    image: woodgrovebank-admin:latest
    build:
      context: .
      dockerfile: Admin/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: admin
    ports:
      - 5001:80
      - 11111:11111
      - 30000:30000

  atm:
    image: woodgrovebank-atm:latest
    build:
      context: .
      dockerfile: ATM/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: atm
    ports:
      - 5002:80
      - 11111:11111
      - 30000:30000

  dashboard:
    image: woodgrovebank-dashboard:latest
    build:
      context: .
      dockerfile: Dashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: api
    ports:
      - 5003:80
      - 11111:11111
      - 30000:30000

  simulations:
    image: woodgrovebank-simulations:latest
    build:
      context: .
      dockerfile: Simulations/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: api
    ports:
      - 5004:80
      - 11111:11111
      - 30000:30000

  orleans-scaler:
    image: orleans-scaler:latest
    build:
      context: .
      dockerfile: Scaler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: orleans-scaler
    ports:
      - 80:80
      - 11111:11111
      - 30000:30000
      
