apiVersion: v1
kind: Service
metadata:
  name: woodgrovebank-admin
spec:
  selector:
    app: woodgrovebank-admin
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: woodgrovebank-admin
  labels:
    orleans/serviceId: woodgrovebank
spec:
  selector:
    matchLabels:
      app: woodgrovebank-admin
      orleans/serviceId: woodgrovebank
  template:
    metadata:
      labels:
        app: woodgrovebank-admin
        orleans/serviceId: woodgrovebank
        orleans/clusterId: woodgrovebank
    spec:
      containers:
      - name: woodgrovebank-admin
        image: woodgrovebank-admin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 30000
        - containerPort: 11111
        env:
          - name: ORLEANS_SERVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ORLEANS_AZURE_STORAGE_CONNECTION_STRING
            valueFrom: 
              secretKeyRef: 
                key: clustering
                name: storage-connection-strings
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Development'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service: 
                name: woodgrovebank-admin
                port: 
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: woodgrovebank-admin-nodeport
spec:
  ports:
  - name: http
    nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: woodgrovebank-admin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
